# Custom Language File for Launcher Customizer

[ejs.app]
title = "PotoGames Launcher"

[ejs.landing]
mediaGitHubURL = ""
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/SdKyHCEEQJ"

[ejs.settings]
sourceGithubLink = "https://github.com/Thinsh0/PotoGames-Launcher"
supportLink = "https://github.com/Thinsh0/PotoGames-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur PotoGames Launcher"
welcomeDescription = ""
welcomeDescCTA = ""
