# Custom Language File for Launcher Customizer

[ejs.app]
title = "PotoGames Launcher"

[ejs.landing]
mediaGitHubURL = ""
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/WmKNnZS4KB"

[ejs.settings]
sourceGithubLink = "https://github.com/Thinsh0/PotoGames-Launcher"
supportLink = "https://github.com/Thinsh0/PotoGames-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le launcher PotoGames"
welcomeDescription = ""
welcomeDescCTA = ""
